issues:
  exclude-dirs:
    #- lib/ringbuf # todo menglc [代码未完善]
    - lib/protobuf # todo menglc [代码未完善]
linters:
  enable:
    - staticcheck
linters-settings:
  staticcheck:
    checks:
      - all # all 表示执行所有的检查
    fail-fast: true # fail-fast 选项表示在发现第一个错误时立即停止检查
