package error

// [系统错误码] lib/system 级别的错误码
var (
	Success = NewError(0x0000).WithName("Success").WithDesc("success-成功")
	// 通用
	Fail              = NewError(0x0101).WithName("Fail").WithDesc("fail-失败")
	Valid             = NewError(0x0102).WithName("Valid").WithDesc("valid-有效")
	Invalid           = NewError(0x0103).WithName("Invalid").WithDesc("invalid-无效")
	Available         = NewError(0x0104).WithName("Available").WithDesc("available-可用")
	Unavailable       = NewError(0x0105).WithName("Unavailable").WithDesc("unavailable-不可用")
	Exist             = NewError(0x0106).WithName("Exist").WithDesc("exist-存在")
	NotExist          = NewError(0x0107).WithName("NotExist").WithDesc("notExist-不存在")
	Legal             = NewError(0x0108).WithName("Legal").WithDesc("legal-合法")
	Illegal           = NewError(0x0109).WithName("Illegal").WithDesc("illegal-非法")
	Permitted         = NewError(0x010a).WithName("Permitted").WithDesc("permitted-允许的")
	Prohibited        = NewError(0x010b).WithName("Prohibited").WithDesc("prohibited-禁止的")
	Expect            = NewError(0x010c).WithName("Expect").WithDesc("expect-期望")
	Unexpected        = NewError(0x010d).WithName("Unexpected").WithDesc("unexpected-不期望")
	Enable            = NewError(0x010e).WithName("Enable").WithDesc("enable-启用")
	Disable           = NewError(0x010f).WithName("Disable").WithDesc("disable-禁用")
	Normal            = NewError(0x0110).WithName("Normal").WithDesc("normal-正常")
	Abnormal          = NewError(0x0111).WithName("Abnormal").WithDesc("abnormal-异常")
	NotTimeout        = NewError(0x0112).WithName("NotTimeout").WithDesc("not-timeout-未超时")
	Timeout           = NewError(0x0113).WithName("Timeout").WithDesc("timeout-超时")
	NotOutOfRange     = NewError(0x0114).WithName("NotOutOfRange").WithDesc("not-out-of-range-未超出范围")
	OutOfRange        = NewError(0x0115).WithName("OutOfRange").WithDesc("out-of-range-超出范围")
	NotConflict       = NewError(0x0116).WithName("NotConflict").WithDesc("not-conflict-未冲突")
	Conflict          = NewError(0x0117).WithName("Conflict").WithDesc("conflict-冲突")
	Matched           = NewError(0x0118).WithName("Matched").WithDesc("matched-匹配")
	Mismatch          = NewError(0x0119).WithName("Mismatch").WithDesc("mismatch-不匹配")
	Implemented       = NewError(0x011a).WithName("Implemented").WithDesc("implemented-已实现")
	NotImplemented    = NewError(0x011b).WithName("NotImplemented").WithDesc("not-implemented-未实现")
	Registered        = NewError(0x011c).WithName("Registered").WithDesc("registered-已注册")
	Unregistered      = NewError(0x011d).WithName("Unregistered").WithDesc("unregistered-未注册")
	Marshal           = NewError(0x011e).WithName("Marshal").WithDesc("marshal-序列化")
	Unmarshal         = NewError(0x011f).WithName("Unmarshal").WithDesc("unmarshal-反序列化")
	Level             = NewError(0x0120).WithName("Level").WithDesc("level-等级")
	LevelNotEnough    = NewError(0x0121).WithName("LevelNotEnough").WithDesc("level-not-enough-等级不足")
	NotDuplicate      = NewError(0x0122).WithName("NotDuplicate").WithDesc("not-duplicate-不重复")
	Duplicate         = NewError(0x0123).WithName("Duplicate").WithDesc("duplicate-重复")
	Idle              = NewError(0x0124).WithName("Idle").WithDesc("idle-空闲")
	Busy              = NewError(0x0125).WithName("Busy").WithDesc("busy-繁忙")
	AdequateResources = NewError(0x0126).WithName("AdequateResources").WithDesc("adequate-resources-资源充足")
	OutOfResources    = NewError(0x0127).WithName("OutOfResources").WithDesc("out-of-resources-资源不足")
	ValidOperation    = NewError(0x0128).WithName("ValidOperation").WithDesc("valid-operation-有效操作")
	InvalidOperation  = NewError(0x0129).WithName("InvalidOperation").WithDesc("invalid-operation-无效操作")
	AdequateCondition = NewError(0x012a).WithName("AdequateCondition").WithDesc("adequate-condition-条件充足")
	IllConditioned    = NewError(0x012b).WithName("IllConditioned").WithDesc("ill-conditioned-条件不足")
	PermissionGranted = NewError(0x012c).WithName("PermissionGranted").WithDesc("permission-granted-有权限")
	PermissionDenied  = NewError(0x012d).WithName("PermissionDenied").WithDesc("permission-denied-没有权限")
	NotFrozen         = NewError(0x012e).WithName("NotFrozen").WithDesc("not-frozen-未冻结")
	Frozen            = NewError(0x012f).WithName("Frozen").WithDesc("frozen-冻结")
	Hit               = NewError(0x0130).WithName("Hit").WithDesc("hit-命中")
	Miss              = NewError(0x0131).WithName("Miss").WithDesc("miss-未命中")
	Length            = NewError(0x0132).WithName("Length").WithDesc("length-长度")
	LengthExceedLimit = NewError(0x0133).WithName("LengthExceedLimit").WithDesc("length-exceed-limit-长度超出限制")
	Quantity          = NewError(0x0134).WithName("Quantity").WithDesc("quantity-数量")
	QuantityLimit     = NewError(0x0135).WithName("QuantityLimit").WithDesc("quantity-limit-数量限制")

	//
	Retry     = NewError(0x0901).WithName("Retry").WithDesc("retry-重试")
	Parameter = NewError(0x0903).WithName("Parameter").WithDesc("parameter-参数")
	Link      = NewError(0x0905).WithName("Link").WithDesc("link-链接")
	System    = NewError(0x0907).WithName("System").WithDesc("system-系统")
	Param     = NewError(0x0909).WithName("Param").WithDesc("parameter-参数")
	Packet    = NewError(0x090b).WithName("Packet").WithDesc("packet-数据包")
	Config    = NewError(0x090d).WithName("Config").WithDesc("config-配置")
	Overload  = NewError(0x090f).WithName("Overload").WithDesc("overload-过载")
	Nil       = NewError(0x0911).WithName("Nil").WithDesc("nil-空")

	// 协程
	GoroutinePanic = NewError(0x0a00).WithName("GoroutinePanic").WithDesc("goroutine-panic-协程-panic")
	GoroutineDone  = NewError(0x0a01).WithName("GoroutineDone").WithDesc("goroutine-done-协程-结束")
	// 函数
	FunctionPanic = NewError(0x0b00).WithName("FunctionPanic").WithDesc("function-panic-函数-panic")
	FunctionDone  = NewError(0x0b01).WithName("FunctionDone").WithDesc("function-done-函数-结束")
	// channel
	ChannelFull      = NewError(0x0c00).WithName("ChannelFull").WithDesc("channel-full-通道-满")
	ChannelEmpty     = newError(0x0c01).WithName("ChannelEmpty").WithDesc("channel-empty-通道-空")
	ChannelNotClosed = NewError(0x0c02).WithName("ChannelNotClosed").WithDesc("channel-not-closed-通道-未关闭")
	ChannelClosed    = NewError(0x0c03).WithName("ChannelClosed").WithDesc("channel-closed-通道-已关闭")
	ChannelNil       = NewError(0x0c04).WithName("ChannelNil").WithDesc("channel-通道-未初始化")

	// 操作
	Insert    = NewError(0xf001).WithName("Insert").WithDesc("insert-插入")
	Find      = NewError(0xf002).WithName("Find").WithDesc("find-查找")
	Update    = NewError(0xf003).WithName("Update").WithDesc("update-更新")
	Delete    = NewError(0xf004).WithName("Delete").WithDesc("delete-删除")
	Send      = NewError(0xf005).WithName("Send").WithDesc("send-发送")
	Receive   = NewError(0xf006).WithName("Receive").WithDesc("receive-接收")
	Configure = NewError(0xf007).WithName("Configure").WithDesc("configure-给配置")

	Unknown = NewError(0xffff).WithName("Unknown").WithDesc("unknown-未知")
	// 0xffff
)
