#!/bin/bash

genMod=go_out      #google.golang.org/protobuf/cmd/protoc-gen-go
#genMod=gofast_out  #github.com/gogo/protobuf/protoc-gen-gofast

########################################################################################################################
#生成 error 文件
genProtoError(){
  #源 目录文件
  srcDirFile="./proto/error.code.proto"
  #目标目录
  desDir="../common/error"
  #目标文件
  desFile="error.go"
  #目标 目录文件
  desDirFile=${desDir}/${desFile}

  echo "/*Code generated by gen.sh. DO NOT EDIT.*/" > ${desDirFile}
  # shellcheck disable=SC2129
  echo "package error" >> ${desDirFile}
  echo "import xerror \"xcore/lib/error\"" >> ${desDirFile}
  echo "var (" >> ${desDirFile}

  #临时文件
	tmpFile=${desDirFile}.tmp

  # shellcheck disable=SC2002
  cat ${srcDirFile} | grep "EC_" | grep -v "//EC_" > ${tmpFile}

	sed -i -r 's/[\s\t]*//g' ${tmpFile}
	sed -i -r 's/\/\// \/\//g' ${tmpFile}
	sed -i -r 's/;/ tagName tagDesc/g' ${tmpFile}

	awk -F " " '{printf("%s = xerror.NewError(%s).WithName(\"%s\").WithDesc(\"%s\") \r\n",$1,$3,$1,$6)}' ${tmpFile} > ${tmpFile}.xxx
	cat ${tmpFile}.xxx > ${tmpFile}

	unlink ${tmpFile}.xxx

	sed -i -r 's/\/\///g' ${tmpFile}
	cat ${tmpFile} >> ${desDirFile}

	unlink ${tmpFile}

  echo ")" >> ${desDirFile}

  #格式化,不显示输出
  go fmt ${desDirFile} > /dev/null
}

########################################################################################################################
#gateway
srcDirFile="./proto/error.code.proto"
protoc --${genMod}=. ${srcDirFile}

########################################################################################################################
#生成 error 文件
genProtoError

echo "生成 protobuf 完成"
#read input

exit 0
